homeassistant:

  customize: !include_dir_merge_named /customizations

  # packages: !include_dir_named packages
  packages: !include_dir_named integrations

  whitelist_external_dirs: 
    - /config
