alias: Living Room Lights - ON
initial_state: 'on'
id: a25d3a2d-3b0a-4a1b-935c-e8d7a1555c2d
trigger:
  - platform: state
    entity_id: sensor.dark_outside
    to: 'true'
  - platform: time
    at: '19:00:00'
condition:
  condition: state
  entity_id: sensor.home_status
  to: 'Occupied'
action:
  - service: light.turn_on
    entity_id: group.livingroom
#    - service: script.notify
#      data:
#        call_dark_outside: 1