alias: Living Room Lights - OFF
initial_state: 'on'
id: a6dc79eb-c677-494b-ac13-4935c10318b7
trigger:
  - platform: time
    at: '21:30:00'
  - platform: state
    entity_id: sensor.dark_outsie
    to: 'false'
  - platform: state
    entity_id: input_boolean.away_mode
    to: 'true'
condition:
  condition: state
  entity_id: light.livingroom
  state: 'on'
action:
  - service: light.turn_off
    entity_id: light.livingroom

#    - service: script.notify
#      data:
#        call_light_outside: 1