alias: Living Room Lights - OFF
initial_state: 'on'
id: a6dc79eb-c677-494b-ac13-4935c10318b7
trigger:
  - platform: state
    entity_id: sensor.dark_outsie
    to: 'false'
  - platform: time
    at: '21:00:00'
action:
  - service: light.turn_off
    entity_id: group.livingroom
#    - service: script.notify
#      data:
#        call_light_outside: 1