alias: Occupancy - Return home
initial_state: 'on'
id: 97b8a48b-4d0d-4cd1-a238-87282600c823
trigger:
  platform: state
  entity_id: group.presence
  to: 'Occupied'
action:
  service: homeassistant.turn_off
  entity_id:
    - input_boolean.holiday_mode
    - input_boolean.away_mode