alias: Backlight - ON (D's Room)
initial_state: 'on'
id: a9993c48-4d15-48d9-86e9-b01ca45e49de
trigger:
  platform: state
  entity_id: sensor.dark_outside
  to: 'true'
condition: 
  - condition: state
    entity_id: group.d_presence
    state: 'home'
  - condition: state
    entity_id: light.wled_backlight
    state: 'off'
action:
  - service: light.turn_on
    entity_id: light.wled_backlight
