alias: sleep lantern
initial_state: 'on'
id: aab0e4cc-9c58-420a-a61d-42fe53516e17
trigger:
  - platform: time
    at: '00:00:00'
condition:
  condition: state
  entity_id: light.d_s_lantern
  state: 'on'
action:
  - service: light.turn_off
    entity_id: light.d_s_lantern
