alias: Lantern - ON
initial_state: 'on'
id: 886b3471-42d1-446d-a8b2-c93e490cdafa
trigger:
  - platform: state
    entity_id: sensor.dark_outside
    to: 'true'
  - platform: time
    at: '19:00:00'
condition:
  - condition: state
    entity_id: light.d_s_lantern
    state: 'off'
  - condition: state
    entity_id: input-boolean.away_mode
    state: 'off'
action:
  - service: light.turn_on
    entity_id: light.d_s_lantern