id: 03224c5c-3342-44f0-a75b-3669197fbed0
alias: Power Problem Notification
trigger:
- platform: numeric_state
  entity_id: sensor.rpi_power_status
  value_template: '{{ state.attributes.value }}'
  above: 0
  for:
    minutes: 3
condition:
action:
- service: persistent_notification.create
  data_template:
    message: "RPI Power reported {{ states.sensor.rpi_power_status.state }}. The state had changed from {{ trigger.from_state.state }} "
    title: RPI PSU Issue
- service: notify.notify
  data_template:
    message: "RPI Power reported {{ states.sensor.rpi_power_status.state }}. The state had  changed from {{ trigger.from_state.state }}"
    title: RPI PSU Issue
- service: ifttt.trigger
  data_template:
    event: Hass.io
    value1: "RPI Power reported {{ states.sensor.rpi_power_status.state }}."