hass_config_check:
  alias: HA Config Check
  sequence:
    - service: homeassistant.turn_on
      entity_id: input_boolean.maintenance_mode
    - service: persistent_notification.create
      data:
        notification_id: "upgrade_alert"
        title: "Hass.io"
        message: "HASS Config is being Checked!"
    - delay: 00:00:02
    - service: homeassistant.check_config
    - service: script.notify
      data:
        no_say: 1
        tell: d
        call_upgrade: 1